name: Publish docs on permaweb

on:
  push:
    branches:
      - 'main'

jobs:
  publish-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - run: bun run docs:build
      - run: bunx permaweb-deploy --ant-process ${{ env.ANT_PROCESS }} --deploy-folder ./docs/docs/dist
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          ANT_PROCESS: "4eMZpmmAGu05o2eW1yPHqIrVYAUbqEpLoAJ0V3F10-o"
